# D:\Jinvexa\Models\LearningPlan.py

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from datetime import datetime
import json

@dataclass
class LearningPhase:
    """A phase in the learning roadmap"""
    phase_number: int
    title: str
    description: str
    topics: List[str]
    estimated_hours: int
    projects: List[str] = field(default_factory=list)
    prerequisites: List[str] = field(default_factory=list)
    difficulty: str = "intermediate"

@dataclass
class LearningPlan:
    """Complete learning plan generated by the agent"""
    
    main_topic: str
    goal: str
    goal_type: str  # understand, build, interview, research, teach, certification
    current_level: str  # beginner, intermediate, advanced
    strengths: List[str]
    knowledge_gaps: List[str]
    estimated_time_hours: int
    roadmap: List[Dict[str, Any]]
    projects: List[Dict[str, Any]]
    quizzes: List[Dict[str, Any]]
    resources: List[Dict[str, str]]
    confidence_scores: Dict[str, float]
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        return {
            "main_topic": self.main_topic,
            "goal": self.goal,
            "goal_type": self.goal_type,
            "current_level": self.current_level,
            "strengths": self.strengths,
            "knowledge_gaps": self.knowledge_gaps,
            "estimated_time_hours": self.estimated_time_hours,
            "roadmap": self.roadmap,
            "projects": self.projects,
            "quizzes": self.quizzes,
            "resources": self.resources,
            "confidence_scores": self.confidence_scores,
            "generated_at": self.generated_at
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> "LearningPlan":
        return cls(**data)
    
    def to_markdown(self) -> str:
        """Convert plan to markdown format for display"""
        md = f"""
# 📚 Learning Plan: {self.main_topic}

## 🎯 Goal: {self.goal}
- **Type:** {self.goal_type}
- **Level:** {self.current_level}
- **Estimated Time:** {self.estimated_time_hours} hours

## ✅ Your Strengths
"""
        for strength in self.strengths:
            md += f"- {strength}\n"
        
        md += f"\n## 📖 Knowledge Gaps\n"
        for gap in self.knowledge_gaps:
            md += f"- {gap}\n"
        
        md += f"\n## 🗺️ Learning Roadmap\n"
        for phase in self.roadmap:
            md += f"\n### Phase {phase.get('phase_number', '')}: {phase.get('title', '')}\n"
            md += f"*{phase.get('description', '')}*\n"
            md += f"**Topics:** {', '.join(phase.get('topics', []))}\n"
            if phase.get('projects'):
                md += f"**Projects:** {', '.join(phase.get('projects', []))}\n"
            md += f"**Estimated Time:** {phase.get('estimated_hours', 0)} hours\n"
        
        if self.projects:
            md += f"\n## 🛠️ Projects\n"
            for project in self.projects:
                md += f"- **{project.get('title', '')}**: {project.get('description', '')}\n"
        
        if self.resources:
            md += f"\n## 📚 Resources\n"
            for resource in self.resources:
                md += f"- [{resource.get('title', '')}]({resource.get('url', '')})\n"
        
        return md